name: animated_quiz_widget_example
description: Example app demonstrating the animated_quiz_widget package
version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_quiz_widget: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true