name: animated_quiz_widget
description: A comprehensive, animated quiz widget package for Flutter with navigation, progress tracking, gradient backgrounds, and customizable styling.
version: 1.0.3
homepage: https://github.com/haseebpvt/animated_quiz_widget
repository: https://github.com/haseebpvt/animated_quiz_widget
issue_tracker: https://github.com/haseebpvt/animated_quiz_widget/issues
documentation: https://github.com/haseebpvt/animated_quiz_widget#readme

topics:
  - quiz
  - widget
  - animation
  - ui
  - flutter-package

environment:
  sdk: ^3.4.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true